name: 'PHP Copy Paste Detector'
description: 'php-cpd'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  args:
    description: 'Arguments to pass to phpcpd'
    required: false
    default: '.'
  exclude:
    description: 'To exclude a directory'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
    - ${{ inputs.exclude }}
